In [1]:
import pandas as pd
import numpy as np
frame = pd.DataFrame(np.random.randn(4,3),
                    columns=list('bde'),
                    index=['台北','台中','台南','高雄'])

frame

           b         d         e
台北 -0.741371 -0.931793 -0.254746
台中 -0.316589 -0.022355  1.708842
台南  0.702245 -1.246562  0.418932
高雄 -0.166047  1.036957 -0.555468

In [2]:
np.abs(frame)

           b         d         e
台北  0.741371  0.931793  0.254746
台中  0.316589  0.022355  1.708842
台南  0.702245  1.246562  0.418932
高雄  0.166047  1.036957  0.555468

In [3]:
np.sum(frame)

/home/vscode/.local/lib/python3.10/site-packages/numpy/core/fromnumeric.py:86: FutureWarning: The behavior of DataFrame.sum with axis=None is deprecated, in a future version this will reduce over both axes and return a scalar. To retain the old behavior, pass axis=0 (or do not pass axis)
  return reduction(axis=axis, out=out, **passkwargs)

b   -0.521761
d   -1.163753
e    1.317559
dtype: float64

In [4]:
frame

           b         d         e
台北 -0.741371 -0.931793 -0.254746
台中 -0.316589 -0.022355  1.708842
台南  0.702245 -1.246562  0.418932
高雄 -0.166047  1.036957 -0.555468

In [7]:
import numpy as np
import pandas as pd

scores = np.random.randint(50,101,size=(50,5))
scores_df = pd.DataFrame(scores,columns=['國文', '英文', '數學', '地理', '歷史'],index=range(1,51))
scores_df

     國文   英文  數學  地理   歷史
1    97   99  79  50  100
2    68   79  75  97   98
3    69   54  62  68   82
4    81   98  78  57   67
5    88   53  66  57   52
6    62   64  99  84   60
7    57   60  71  57   83
8    60   52  78  92   95
9    53   94  75  50   78
10   53   70  83  69   77
11   75   60  51  73   72
12   64   61  52  61   67
13   93   52  68  71   71
14   98   83  60  78   64
15   53   82  83  88   54
16   92   63  72  73   96
17   91   65  52  63   78
18   72   50  51  97  100
19   55   88  74  93   83
20   59   75  90  61   84
21   57   96  86  69   64
22   71   59  93  69   53
23   69   84  74  91  100
24   59   52  64  99   86
25   99   57  97  50   89
26   53   97  99  94   93
27  100   70  57  69   84
28   90   89  54  76   93
29   63   57  91  62   79
30   69   72  88  92   74
31   80   81  95  62   53
32   68   82  79  88   70
33   80   67  61  90   99
34   91   68  76  65   96
35   50   80  82  73   59
36   52   80  58  83   86
37   62   90  90  77   74
38   88   59  54  83   85
39   98  100  99  95   97
40   62   68  72  67   68
41   92   99  65  55   88
42   63   92  60  68   85
43   51   87  65  51   86
44   61   84  61  93   65
45   50   76  91  79   63
46   57   71  74  82   76
47   63   55  87  91   71
48   87   67  99  71  100
49   93   92  55  75   52
50   93   71  82  86   72

In [9]:
# dataframe使用統計的方法,sum,mean,max,min,median,count,std
scores_sum = scores_df.sum(axis=1)
#scores_average = scores_sum / 5.0
scores_average = scores_df.mean(axis=1)
scores_average

1     133.571429
2     131.057143
3     105.285714
4     119.742857
5      99.314286
6     115.971429
7     103.085714
8     118.485714
9     110.000000
10    110.628571
11    104.028571
12     95.857143
13    111.571429
14    120.371429
15    113.142857
16    124.457143
17    109.685714
18    116.285714
19    123.514286
20    115.971429
21    116.914286
22    108.428571
23    131.371429
24    113.142857
25    123.200000
26    137.028571
27    119.428571
28    126.342857
29    110.628571
30    124.142857
31    116.600000
32    121.628571
33    124.771429
34    124.457143
35    108.114286
36    112.828571
37    123.514286
38    115.971429
39    153.685714
40    105.914286
41    125.400000
42    115.657143
43    106.857143
44    114.400000
45    112.828571
46    113.142857
47    115.342857
48    133.257143
49    115.342857
50    126.971429
dtype: float64

In [8]:
# dataframe使用統計的方法,sum,mean,max,min,median,count,std
scores_sum = scores_df.sum(axis=1)
#scores_average = scores_sum / 5.0
scores_average = scores_df.mean(axis=1)
scores_average
scores_df['總分'] = scores_sum
scores_df['平均'] = scores_average
scores_df

     國文   英文  數學  地理   歷史   總分    平均
1    97   99  79  50  100  425  85.0
2    68   79  75  97   98  417  83.4
3    69   54  62  68   82  335  67.0
4    81   98  78  57   67  381  76.2
5    88   53  66  57   52  316  63.2
6    62   64  99  84   60  369  73.8
7    57   60  71  57   83  328  65.6
8    60   52  78  92   95  377  75.4
9    53   94  75  50   78  350  70.0
10   53   70  83  69   77  352  70.4
11   75   60  51  73   72  331  66.2
12   64   61  52  61   67  305  61.0
13   93   52  68  71   71  355  71.0
14   98   83  60  78   64  383  76.6
15   53   82  83  88   54  360  72.0
16   92   63  72  73   96  396  79.2
17   91   65  52  63   78  349  69.8
18   72   50  51  97  100  370  74.0
19   55   88  74  93   83  393  78.6
20   59   75  90  61   84  369  73.8
21   57   96  86  69   64  372  74.4
22   71   59  93  69   53  345  69.0
23   69   84  74  91  100  418  83.6
24   59   52  64  99   86  360  72.0
25   99   57  97  50   89  392  78.4
26   53   97  99  94   93  436  87.2
27  100   70  57  69   84  380  76.0
28   90   89  54  76   93  402  80.4
29   63   57  91  62   79  352  70.4
30   69   72  88  92   74  395  79.0
31   80   81  95  62   53  371  74.2
32   68   82  79  88   70  387  77.4
33   80   67  61  90   99  397  79.4
34   91   68  76  65   96  396  79.2
35   50   80  82  73   59  344  68.8
36   52   80  58  83   86  359  71.8
37   62   90  90  77   74  393  78.6
38   88   59  54  83   85  369  73.8
39   98  100  99  95   97  489  97.8
40   62   68  72  67   68  337  67.4
41   92   99  65  55   88  399  79.8
42   63   92  60  68   85  368  73.6
43   51   87  65  51   86  340  68.0
44   61   84  61  93   65  364  72.8
45   50   76  91  79   63  359  71.8
46   57   71  74  82   76  360  72.0
47   63   55  87  91   71  367  73.4
48   87   67  99  71  100  424  84.8
49   93   92  55  75   52  367  73.4
50   93   71  82  86   72  404  80.8

In [11]:
scores_df

     國文   英文  數學  地理   歷史      總分    平均
1    97   99  79  50  100   935.0  85.0
2    68   79  75  97   98   917.4  83.4
3    69   54  62  68   82   737.0  67.0
4    81   98  78  57   67   838.2  76.2
5    88   53  66  57   52   695.2  63.2
6    62   64  99  84   60   811.8  73.8
7    57   60  71  57   83   721.6  65.6
8    60   52  78  92   95   829.4  75.4
9    53   94  75  50   78   770.0  70.0
10   53   70  83  69   77   774.4  70.4
11   75   60  51  73   72   728.2  66.2
12   64   61  52  61   67   671.0  61.0
13   93   52  68  71   71   781.0  71.0
14   98   83  60  78   64   842.6  76.6
15   53   82  83  88   54   792.0  72.0
16   92   63  72  73   96   871.2  79.2
17   91   65  52  63   78   767.8  69.8
18   72   50  51  97  100   814.0  74.0
19   55   88  74  93   83   864.6  78.6
20   59   75  90  61   84   811.8  73.8
21   57   96  86  69   64   818.4  74.4
22   71   59  93  69   53   759.0  69.0
23   69   84  74  91  100   919.6  83.6
24   59   52  64  99   86   792.0  72.0
25   99   57  97  50   89   862.4  78.4
26   53   97  99  94   93   959.2  87.2
27  100   70  57  69   84   836.0  76.0
28   90   89  54  76   93   884.4  80.4
29   63   57  91  62   79   774.4  70.4
30   69   72  88  92   74   869.0  79.0
31   80   81  95  62   53   816.2  74.2
32   68   82  79  88   70   851.4  77.4
33   80   67  61  90   99   873.4  79.4
34   91   68  76  65   96   871.2  79.2
35   50   80  82  73   59   756.8  68.8
36   52   80  58  83   86   789.8  71.8
37   62   90  90  77   74   864.6  78.6
38   88   59  54  83   85   811.8  73.8
39   98  100  99  95   97  1075.8  97.8
40   62   68  72  67   68   741.4  67.4
41   92   99  65  55   88   877.8  79.8
42   63   92  60  68   85   809.6  73.6
43   51   87  65  51   86   748.0  68.0
44   61   84  61  93   65   800.8  72.8
45   50   76  91  79   63   789.8  71.8
46   57   71  74  82   76   792.0  72.0
47   63   55  87  91   71   807.4  73.4
48   87   67  99  71  100   932.8  84.8
49   93   92  55  75   52   807.4  73.4
50   93   71  82  86   72   888.8  80.8

In [12]:
scores_df[['國文', '英文', '數學', '地理', '歷史']]

     國文   英文  數學  地理   歷史
1    97   99  79  50  100
2    68   79  75  97   98
3    69   54  62  68   82
4    81   98  78  57   67
5    88   53  66  57   52
6    62   64  99  84   60
7    57   60  71  57   83
8    60   52  78  92   95
9    53   94  75  50   78
10   53   70  83  69   77
11   75   60  51  73   72
12   64   61  52  61   67
13   93   52  68  71   71
14   98   83  60  78   64
15   53   82  83  88   54
16   92   63  72  73   96
17   91   65  52  63   78
18   72   50  51  97  100
19   55   88  74  93   83
20   59   75  90  61   84
21   57   96  86  69   64
22   71   59  93  69   53
23   69   84  74  91  100
24   59   52  64  99   86
25   99   57  97  50   89
26   53   97  99  94   93
27  100   70  57  69   84
28   90   89  54  76   93
29   63   57  91  62   79
30   69   72  88  92   74
31   80   81  95  62   53
32   68   82  79  88   70
33   80   67  61  90   99
34   91   68  76  65   96
35   50   80  82  73   59
36   52   80  58  83   86
37   62   90  90  77   74
38   88   59  54  83   85
39   98  100  99  95   97
40   62   68  72  67   68
41   92   99  65  55   88
42   63   92  60  68   85
43   51   87  65  51   86
44   61   84  61  93   65
45   50   76  91  79   63
46   57   71  74  82   76
47   63   55  87  91   71
48   87   67  99  71  100
49   93   92  55  75   52
50   93   71  82  86   72

In [20]:
#scores_df[['國文', '英文', '數學', '地理', '歷史']]
from pandas import Series
def get_level(s:Series):
    return'甲'

scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_level,axis=1)

1     甲
2     甲
3     甲
4     甲
5     甲
6     甲
7     甲
8     甲
9     甲
10    甲
11    甲
12    甲
13    甲
14    甲
15    甲
16    甲
17    甲
18    甲
19    甲
20    甲
21    甲
22    甲
23    甲
24    甲
25    甲
26    甲
27    甲
28    甲
29    甲
30    甲
31    甲
32    甲
33    甲
34    甲
35    甲
36    甲
37    甲
38    甲
39    甲
40    甲
41    甲
42    甲
43    甲
44    甲
45    甲
46    甲
47    甲
48    甲
49    甲
50    甲
dtype: object

In [23]:
#scores_df[['國文', '英文', '數學', '地理', '歷史']]
from pandas import Series
def get_level(s:Series):
    print(s.min)
    return'甲'

scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_level,axis=1)

<bound method Series.min of 國文     97
英文     99
數學     79
地理     50
歷史    100
Name: 1, dtype: int64>
<bound method Series.min of 國文    68
英文    79
數學    75
地理    97
歷史    98
Name: 2, dtype: int64>
<bound method Series.min of 國文    69
英文    54
數學    62
地理    68
歷史    82
Name: 3, dtype: int64>
<bound method Series.min of 國文    81
英文    98
數學    78
地理    57
歷史    67
Name: 4, dtype: int64>
<bound method Series.min of 國文    88
英文    53
數學    66
地理    57
歷史    52
Name: 5, dtype: int64>
<bound method Series.min of 國文    62
英文    64
數學    99
地理    84
歷史    60
Name: 6, dtype: int64>
<bound method Series.min of 國文    57
英文    60
數學    71
地理    57
歷史    83
Name: 7, dtype: int64>
<bound method Series.min of 國文    60
英文    52
數學    78
地理    92
歷史    95
Name: 8, dtype: int64>
<bound method Series.min of 國文    53
英文    94
數學    75
地理    50
歷史    78
Name: 9, dtype: int64>
<bound method Series.min of 國文    53
英文    70
數學    83
地理    69
歷史    77
Name: 10, dtype: int64>
<bound method Series.min of 國文    75
英文    60
數學    51
地理    73
歷史    72
Name: 11, dtype: int64>
<bound method Series.min of 國文    64
英文    61
數學    52
地理    61
歷史    67
Name: 12, dtype: int64>
<bound method Series.min of 國文    93
英文    52
數學    68
地理    71
歷史    71
Name: 13, dtype: int64>
<bound method Series.min of 國文    98
英文    83
數學    60
地理    78
歷史    64
Name: 14, dtype: int64>
<bound method Series.min of 國文    53
英文    82
數學    83
地理    88
歷史    54
Name: 15, dtype: int64>
<bound method Series.min of 國文    92
英文    63
數學    72
地理    73
歷史    96
Name: 16, dtype: int64>
<bound method Series.min of 國文    91
英文    65
數學    52
地理    63
歷史    78
Name: 17, dtype: int64>
<bound method Series.min of 國文     72
英文     50
數學     51
地理     97
歷史    100
Name: 18, dtype: int64>
<bound method Series.min of 國文    55
英文    88
數學    74
地理    93
歷史    83
Name: 19, dtype: int64>
<bound method Series.min of 國文    59
英文    75
數學    90
地理    61
歷史    84
Name: 20, dtype: int64>
<bound method Series.min of 國文    57
英文    96
數學    86
地理    69
歷史    64
Name: 21, dtype: int64>
<bound method Series.min of 國文    71
英文    59
數學    93
地理    69
歷史    53
Name: 22, dtype: int64>
<bound method Series.min of 國文     69
英文     84
數學     74
地理     91
歷史    100
Name: 23, dtype: int64>
<bound method Series.min of 國文    59
英文    52
數學    64
地理    99
歷史    86
Name: 24, dtype: int64>
<bound method Series.min of 國文    99
英文    57
數學    97
地理    50
歷史    89
Name: 25, dtype: int64>
<bound method Series.min of 國文    53
英文    97
數學    99
地理    94
歷史    93
Name: 26, dtype: int64>
<bound method Series.min of 國文    100
英文     70
數學     57
地理     69
歷史     84
Name: 27, dtype: int64>
<bound method Series.min of 國文    90
英文    89
數學    54
地理    76
歷史    93
Name: 28, dtype: int64>
<bound method Series.min of 國文    63
英文    57
數學    91
地理    62
歷史    79
Name: 29, dtype: int64>
<bound method Series.min of 國文    69
英文    72
數學    88
地理    92
歷史    74
Name: 30, dtype: int64>
<bound method Series.min of 國文    80
英文    81
數學    95
地理    62
歷史    53
Name: 31, dtype: int64>
<bound method Series.min of 國文    68
英文    82
數學    79
地理    88
歷史    70
Name: 32, dtype: int64>
<bound method Series.min of 國文    80
英文    67
數學    61
地理    90
歷史    99
Name: 33, dtype: int64>
<bound method Series.min of 國文    91
英文    68
數學    76
地理    65
歷史    96
Name: 34, dtype: int64>
<bound method Series.min of 國文    50
英文    80
數學    82
地理    73
歷史    59
Name: 35, dtype: int64>
<bound method Series.min of 國文    52
英文    80
數學    58
地理    83
歷史    86
Name: 36, dtype: int64>
<bound method Series.min of 國文    62
英文    90
數學    90
地理    77
歷史    74
Name: 37, dtype: int64>
<bound method Series.min of 國文    88
英文    59
數學    54
地理    83
歷史    85
Name: 38, dtype: int64>
<bound method Series.min of 國文     98
英文    100
數學     99
地理     95
歷史     97
Name: 39, dtype: int64>
<bound method Series.min of 國文    62
英文    68
數學    72
地理    67
歷史    68
Name: 40, dtype: int64>
<bound method Series.min of 國文    92
英文    99
數學    65
地理    55
歷史    88
Name: 41, dtype: int64>
<bound method Series.min of 國文    63
英文    92
數學    60
地理    68
歷史    85
Name: 42, dtype: int64>
<bound method Series.min of 國文    51
英文    87
數學    65
地理    51
歷史    86
Name: 43, dtype: int64>
<bound method Series.min of 國文    61
英文    84
數學    61
地理    93
歷史    65
Name: 44, dtype: int64>
<bound method Series.min of 國文    50
英文    76
數學    91
地理    79
歷史    63
Name: 45, dtype: int64>
<bound method Series.min of 國文    57
英文    71
數學    74
地理    82
歷史    76
Name: 46, dtype: int64>
<bound method Series.min of 國文    63
英文    55
數學    87
地理    91
歷史    71
Name: 47, dtype: int64>
<bound method Series.min of 國文     87
英文     67
數學     99
地理     71
歷史    100
Name: 48, dtype: int64>
<bound method Series.min of 國文    93
英文    92
數學    55
地理    75
歷史    52
Name: 49, dtype: int64>
<bound method Series.min of 國文    93
英文    71
數學    82
地理    86
歷史    72
Name: 50, dtype: int64>

1     甲
2     甲
3     甲
4     甲
5     甲
6     甲
7     甲
8     甲
9     甲
10    甲
11    甲
12    甲
13    甲
14    甲
15    甲
16    甲
17    甲
18    甲
19    甲
20    甲
21    甲
22    甲
23    甲
24    甲
25    甲
26    甲
27    甲
28    甲
29    甲
30    甲
31    甲
32    甲
33    甲
34    甲
35    甲
36    甲
37    甲
38    甲
39    甲
40    甲
41    甲
42    甲
43    甲
44    甲
45    甲
46    甲
47    甲
48    甲
49    甲
50    甲
dtype: object

In [25]:
#scores_df[['國文', '英文', '數學', '地理', '歷史']]
#dataFrame應用自訂的function
from pandas import Series

def get_level(s:Series):
    average = s.mean()
    if average < 60:
        return '不及格'
    elif average < 80:
        return '甲'
    else:
        return '優'


scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_level,axis=1)

1     優
2     優
3     甲
4     甲
5     甲
6     甲
7     甲
8     甲
9     甲
10    甲
11    甲
12    甲
13    甲
14    甲
15    甲
16    甲
17    甲
18    甲
19    甲
20    甲
21    甲
22    甲
23    優
24    甲
25    甲
26    優
27    甲
28    優
29    甲
30    甲
31    甲
32    甲
33    甲
34    甲
35    甲
36    甲
37    甲
38    甲
39    優
40    甲
41    甲
42    甲
43    甲
44    甲
45    甲
46    甲
47    甲
48    優
49    甲
50    優
dtype: object

In [24]:
#scores_df[['國文', '英文', '數學', '地理', '歷史']]
#dataFrame應用自訂的function
from pandas import Series

def get_level(s:Series):
    average = s.mean()
    if average < 60:
        return '不及格'
    elif average < 80:
        return '甲'
    else:
        return '優'


scores_df['等級'] = scores_df[['國文', '英文', '數學', '地理', '歷史']].apply(get_level,axis=1)

In [26]:
scores_df

     國文   英文  數學  地理   歷史      總分    平均 等級
1    97   99  79  50  100   935.0  85.0  優
2    68   79  75  97   98   917.4  83.4  優
3    69   54  62  68   82   737.0  67.0  甲
4    81   98  78  57   67   838.2  76.2  甲
5    88   53  66  57   52   695.2  63.2  甲
6    62   64  99  84   60   811.8  73.8  甲
7    57   60  71  57   83   721.6  65.6  甲
8    60   52  78  92   95   829.4  75.4  甲
9    53   94  75  50   78   770.0  70.0  甲
10   53   70  83  69   77   774.4  70.4  甲
11   75   60  51  73   72   728.2  66.2  甲
12   64   61  52  61   67   671.0  61.0  甲
13   93   52  68  71   71   781.0  71.0  甲
14   98   83  60  78   64   842.6  76.6  甲
15   53   82  83  88   54   792.0  72.0  甲
16   92   63  72  73   96   871.2  79.2  甲
17   91   65  52  63   78   767.8  69.8  甲
18   72   50  51  97  100   814.0  74.0  甲
19   55   88  74  93   83   864.6  78.6  甲
20   59   75  90  61   84   811.8  73.8  甲
21   57   96  86  69   64   818.4  74.4  甲
22   71   59  93  69   53   759.0  69.0  甲
23   69   84  74  91  100   919.6  83.6  優
24   59   52  64  99   86   792.0  72.0  甲
25   99   57  97  50   89   862.4  78.4  甲
26   53   97  99  94   93   959.2  87.2  優
27  100   70  57  69   84   836.0  76.0  甲
28   90   89  54  76   93   884.4  80.4  優
29   63   57  91  62   79   774.4  70.4  甲
30   69   72  88  92   74   869.0  79.0  甲
31   80   81  95  62   53   816.2  74.2  甲
32   68   82  79  88   70   851.4  77.4  甲
33   80   67  61  90   99   873.4  79.4  甲
34   91   68  76  65   96   871.2  79.2  甲
35   50   80  82  73   59   756.8  68.8  甲
36   52   80  58  83   86   789.8  71.8  甲
37   62   90  90  77   74   864.6  78.6  甲
38   88   59  54  83   85   811.8  73.8  甲
39   98  100  99  95   97  1075.8  97.8  優
40   62   68  72  67   68   741.4  67.4  甲
41   92   99  65  55   88   877.8  79.8  甲
42   63   92  60  68   85   809.6  73.6  甲
43   51   87  65  51   86   748.0  68.0  甲
44   61   84  61  93   65   800.8  72.8  甲
45   50   76  91  79   63   789.8  71.8  甲
46   57   71  74  82   76   792.0  72.0  甲
47   63   55  87  91   71   807.4  73.4  甲
48   87   67  99  71  100   932.8  84.8  優
49   93   92  55  75   52   807.4  73.4  甲
50   93   71  82  86   72   888.8  80.8  優